FROM mariadb:11.8.6

COPY init.sh /docker-entrypoint-initdb.d/init.sh
RUN apt-get update && apt-get install -y dos2unix \
    && dos2unix /docker-entrypoint-initdb.d/init.sh \
    && chmod +x /docker-entrypoint-initdb.d/init.sh \
    && apt-get remove -y dos2unix && rm -rf /var/lib/apt/lists/*
