version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
      - ./apache-conf:/etc/apache2/sites-enabled
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./mariadb-conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
    command: --group-concat-max-len=4294967295
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    volumes:
      - ./phpmyadmin-conf:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      db:
        condition: service_healthy